# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  #  name: repo-name

  # A short description of the repository that will show up on GitHub
  description: ⚙️ Shared settings between AtomicGo repositories

  # A URL with more information about the repository
  homepage: https://atomicgo.dev

  # A comma-separated list of topics to set on the repository
  topics: atomicgo, go, golang, golang-library

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: false

  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false

  # Either `true` to enable downloads for this repository, `false` to disable them.
  has_downloads: true

  # Updates the default branch for this repository.
  default_branch: main

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: false

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: false

# Labels: define labels for Issues and Pull Requests
labels:
  - name: bug
    color: d73a4a
  - name: breaking
    color: ff0000
  - name: fix
    color: 0052cc
  - name: docs
    color: 0075ca
  - name: duplicate
    color: cfd3d7
  - name: feature
    color: 006B75
  - name: proposal
    color: 008672
  - name: good first issues
    color: 7057ff
  - name: help wanted
    color: 008672
  - name: in progress
    color: 5319e7
  - name: invalid
    color: e4e669
  - name: question
    color: d876e3

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: false
      required_linear_history: false
      restrictions:
        apps: []
        users: []
        teams: []
